<a href="https://colab.research.google.com/github/PacktPublishing/Hands-On-Computer-Vision-with-PyTorch/blob/master/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


The data type of all elements within a tensor is the same. That means if a
tensor contains data of different data types (such as a Boolean, an integer,
and a float), the entire tensor is coerced to the most generic data type

In [4]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])
print(x.dtype)

tensor([0., 1., 2.])
torch.float32


In [5]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Generate three rows and four columns of values between 0 and 10
(including the low value but not including the high value):

In [7]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[9, 8, 7, 7],
        [6, 3, 2, 2],
        [7, 9, 8, 5]])

Generate random numbers between 0 and 1 with three rows and four
columns:

In [9]:
torch.rand(3, 4)

tensor([[0.7522, 0.9333, 0.0276, 0.6165],
        [0.8416, 0.0856, 0.3500, 0.3140],
        [0.3648, 0.0983, 0.1022, 0.4029]])

Generate numbers that follow a **normal distribution** with three rows and
four columns:

In [10]:
torch.randn((3,4))

tensor([[ 0.7292, -0.3270, -0.8470, -0.2604],
        [-0.4218, -0.4276, -0.1886,  0.0347],
        [-0.2472,  0.4392, -1.6353, -0.9711]])

we can directly convert a NumPy array into a Torch tensor using
```torch.tensor(<numpy-array>)```:

In [11]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
